//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#routes
////
//// DO NOT EDIT THIS FILE. If you would like to use plain
//// pattern matching over this compiled route approach, take a
//// look at the docs link below detailing how to do so.
////
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#direct-pattern-matching
////

import app/http/controllers/api/electricity/electricity_controller as api_electricity_electricity_controller
import gleam/http.{Post}
import glimr/http/response

pub fn routes(path, method, ctx) {
  case path {
    ["api", "forms"] ->
      case method {
        Post -> api_electricity_electricity_controller.store(ctx)
        _ -> response.method_not_allowed([Post])
      }

    _ -> response.not_found()
  }
}
