//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#routes
////
//// DO NOT EDIT THIS FILE. If you would like to use plain
//// pattern matching over this compiled route approach, take a
//// look at the docs link below detailing how to do so.
////
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#direct-pattern-matching
////

import app/http/controllers/api/user_controller as api_user_controller
import gleam/http.{Get, Post}
import glimr/http/response

pub fn routes(path, method, ctx) {
  case path {
    ["api", "users"] ->
      case method {
        Get -> api_user_controller.show(ctx)
        Post -> api_user_controller.store(ctx)
        _ -> response.method_not_allowed([Get, Post])
      }

    _ -> response.not_found()
  }
}
