//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import app/app.{type App}
import compiled/loom/components/layouts/app as components_layouts_app
import gleam/result
import gleam/string_tree.{type StringTree}
import glimr/http/context.{type Context}
import glimr/http/response.{type Response}
import glimr/loom/runtime
import glimr/session

pub fn render(ctx ctx: Context(App)) -> StringTree {
  string_tree.concat([
    components_layouts_app.render(
      slot_footer: string_tree.new(),
      slot_footer_scripts: string_tree.new(),
      slot_head: string_tree.new(),
      slot_meta_title: string_tree.new(),
      slot: string_tree.from_strings([
        "\n  <h1>",
        runtime.display(
          session.get(ctx.session, "message") |> result.unwrap(""),
        ),
        "</h1>\n",
      ]),
      attributes: [],
    ),
    string_tree.from_strings(["\n"]),
  ])
}

pub fn ok(ctx ctx: Context(App)) -> Response {
  render(ctx: ctx) |> response.string_tree(200)
}
