//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import app/app.{type App}
import compiled/loom/components/button as components_button
import compiled/loom/components/layouts/app as components_layouts_app
import database/main/models/user/gen/user
import gleam/string_tree.{type StringTree}
import glimr/http/context
import glimr/http/response.{type Response}
import glimr/loom/runtime
import glimr/session

pub fn render(
  ctx ctx: context.Context(App),
  user user: user.User,
) -> StringTree {
  string_tree.concat([
    components_layouts_app.render(
      slot_meta_title: string_tree.from_strings(["Dashboard"]),
      slot_footer: string_tree.new(),
      slot_footer_scripts: string_tree.new(),
      slot_head: string_tree.new(),
      slot: string_tree.concat([
        string_tree.from_strings([
          "\n  ",
          "\n\n  <div class=\"flex items-center justify-center min-h-screen bg-gray-50\">\n    <div class=\"w-full max-w-lg p-8 bg-white rounded-lg shadow-md\">\n      ",
        ]),
        case session.has_flash(ctx.session, "message") {
          True ->
            string_tree.from_strings([
              "<div",
              " "
                <> runtime.render_attributes([
                runtime.Attribute(
                  "class",
                  "mb-4 p-3 bg-green-100 border border-green-300 text-green-700 rounded",
                ),
              ]),
              ">",
              "\n        ",
              runtime.display(session.get_flash(ctx.session, "message")),
              "\n      ",
              "</div>",
            ])
          False -> string_tree.new()
        },
        string_tree.from_strings([
          "\n\n      <h1 class=\"text-2xl font-bold text-gray-900 mb-2\">Dashboard</h1>\n\n      <p class=\"text-gray-600 mb-6\">\n        Welcome, ",
          runtime.display(user.email),
          "\n      </p>\n\n      <form method=\"post\" action=\"/logout\">\n        ",
        ]),
        components_button.render(
          variant: "secondary",
          href: "",
          slot: string_tree.from_strings(["Logout"]),
          attributes: [
            runtime.Attribute("type", "submit"),
            runtime.Attribute("variant", "secondary"),
          ],
        ),
        string_tree.from_strings(["\n      </form>\n    </div>\n  </div>\n"]),
      ]),
      attributes: [],
    ),
    string_tree.from_strings(["\n"]),
  ])
}

pub fn ok(ctx ctx: context.Context(App), user user: user.User) -> Response {
  render(ctx: ctx, user: user) |> response.string_tree(200)
}
