//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import app/app.{type App}
import compiled/loom/components/button as components_button
import compiled/loom/components/input as components_input
import compiled/loom/components/layouts/app as components_layouts_app
import compiled/loom/components/link as components_link
import gleam/string_tree.{type StringTree}
import glimr/http/context
import glimr/http/response.{type Response}
import glimr/loom/runtime
import glimr/session

pub fn render(ctx ctx: context.Context(App)) -> StringTree {
  string_tree.concat([
    components_layouts_app.render(
      slot_meta_title: string_tree.from_strings(["Register"]),
      slot_footer: string_tree.new(),
      slot_footer_scripts: string_tree.new(),
      slot_head: string_tree.new(),
      slot: string_tree.concat([
        string_tree.from_strings([
          "\n  ",
          "\n\n  <div class=\"flex items-center justify-center min-h-screen bg-mist-50\">\n    <div class=\"w-full max-w-md p-8 bg-white rounded-lg shadow-md\">\n      <h1 class=\"text-[22px] font-bold text-center text-mist-800 mb-6\">\n        Register now\n      </h1>\n\n      ",
        ]),
        case session.has_flash(ctx.session, "error") {
          True ->
            string_tree.from_strings([
              "<div",
              " "
                <> runtime.render_attributes([
                runtime.Attribute(
                  "class",
                  "mb-4 p-3 bg-red-100 border border-red-300 text-red-700 rounded",
                ),
              ]),
              ">",
              "\n        ",
              runtime.display(session.get_flash(ctx.session, "error")),
              "\n      ",
              "</div>",
            ])
          False -> string_tree.new()
        },
        string_tree.from_strings([
          "\n\n      <form method=\"post\" action=\"/register\">\n        <div class=\"mb-4\">\n          ",
        ]),
        components_input.render(
          id: "email",
          name: "email",
          label: "Email Address",
          session: ctx.session,
          attributes: [
            runtime.Attribute("id", "email"),
            runtime.Attribute("name", "email"),
            runtime.Attribute("type", "email"),
            runtime.Attribute("label", "Email Address"),
            runtime.Attribute("placeholder", "name@email.com"),
          ],
        ),
        string_tree.from_strings([
          "\n        </div>\n\n        <div class=\"mb-4\">\n          ",
        ]),
        components_input.render(
          id: "first_name",
          name: "first_name",
          label: "First name",
          session: ctx.session,
          attributes: [
            runtime.Attribute("id", "first_name"),
            runtime.Attribute("name", "first_name"),
            runtime.Attribute("type", "text"),
            runtime.Attribute("label", "First name"),
          ],
        ),
        string_tree.from_strings([
          "\n        </div>\n\n        <div class=\"mb-4\">\n          ",
        ]),
        components_input.render(
          id: "last_name",
          name: "last_name",
          label: "Last name",
          session: ctx.session,
          attributes: [
            runtime.Attribute("id", "last_name"),
            runtime.Attribute("name", "last_name"),
            runtime.Attribute("type", "text"),
            runtime.Attribute("label", "Last name"),
          ],
        ),
        string_tree.from_strings([
          "\n        </div>\n\n        <div class=\"mb-4\">\n          ",
        ]),
        components_input.render(
          id: "password",
          name: "password",
          label: "Password",
          session: ctx.session,
          attributes: [
            runtime.Attribute("id", "password"),
            runtime.Attribute("name", "password"),
            runtime.Attribute("type", "password"),
            runtime.Attribute("label", "Password"),
            runtime.Attribute("placeholder", "super-secret-password"),
          ],
        ),
        string_tree.from_strings([
          "\n        </div>\n\n        <div class=\"mb-6\">\n          ",
        ]),
        components_input.render(
          id: "password_confirmation",
          name: "password_confirmation",
          label: "Confirm Password",
          session: ctx.session,
          attributes: [
            runtime.Attribute("id", "password_confirmation"),
            runtime.Attribute("name", "password_confirmation"),
            runtime.Attribute("type", "password"),
            runtime.Attribute("label", "Confirm Password"),
            runtime.Attribute("placeholder", "super-secret-password"),
          ],
        ),
        string_tree.from_strings(["\n        </div>\n\n        "]),
        components_button.render(
          variant: "",
          href: "",
          slot: string_tree.from_strings(["Register"]),
          attributes: [runtime.Attribute("type", "submit")],
        ),
        string_tree.from_strings([
          "\n      </form>\n\n      <p class=\"mt-4 text-center text-sm text-mist-500\">\n        Already have an account?\n        ",
        ]),
        components_link.render(
          variant: "",
          slot: string_tree.from_strings(["Login"]),
          attributes: [
            runtime.Attribute("href", "/login"),
            runtime.Attribute("class", "ml-0.5"),
          ],
        ),
        string_tree.from_strings(["\n      </p>\n    </div>\n  </div>\n"]),
      ]),
      attributes: [],
    ),
    string_tree.from_strings(["\n"]),
  ])
}

pub fn ok(ctx ctx: context.Context(App)) -> Response {
  render(ctx: ctx) |> response.string_tree(200)
}
